### ISSUE TITLE
Rental papers are not given upon purchase

### ISSUE THREAD

**Issue by Tamer173** [Geenensq/qb-rental#2]
**cannot return the rental car**

![image](https://user-images.githubusercontent.com/105336574/181211094-eea2e21d-3997-4510-a528-e3d6ae1eebd6.png)

**Rental paper (item) dosent appear in inventory so that the above problem occurs**

![image](https://user-images.githubusercontent.com/105336574/181211385-d57c8a17-f850-4994-950d-fe5c40c99169.png)

**Comment by amgmacht** [comment]
did you also add the item to qb-core/shared/items.lua ?

`["rentalpapers"]				 = {["name"] = "rentalpapers", 					["label"] = "Rental Papers", 			["weight"] = 50, 		["type"] = "item", 		["image"] = "rentalpapers.png", 		["unique"] = true, 		["useable"] = false, 	["shouldClose"] = false, 	["combinable"] = nil, 	["description"] = "This car was taken out through car rental."}`

**Comment by Tamer173** [comment]
I have followed everything in the read me file so the problem is not at my end.
Steps i have done are :
1. Added the following code to qb-core in items.lua File :
`["rentalpapers"]				 = {["name"] = "rentalpapers", 					["label"] = "Rental Papers", 			["weight"] = 50, 		["type"] = "item", 		["image"] = "rentalpapers.png", 		["unique"] = true, 		["useable"] = false, 	["shouldClose"] = false, 	["combinable"] = nil, 	["description"] = "This car was taken out through car rental."}`

2. Added the following code to qb-inventory -> html -> js -> app.js  File :
          ```
} else if (itemData.name == "rentalpapers") {
            $(".item-info-title").html('<p>' + itemData.label + '</p>')
            $(".item-info-description").html('<p><strong>Plate: </strong><span>'+ itemData.info.label + '</span></p>');
```
3. Added the image to qb-inventory -> html -> images-> app.js  Folder :
rentalpapers.png

**Comment by Tamer173** [comment]
> did you also add the item to qb-core/shared/items.lua ?
> 
> `["rentalpapers"] = {["name"] = "rentalpapers", ["label"] = "Rental Papers", ["weight"] = 50, ["type"] = "item", ["image"] = "rentalpapers.png", ["unique"] = true, ["useable"] = false, ["shouldClose"] = false, ["combinable"] = nil, ["description"] = "This car was taken out through car rental."}`

yes

**Comment by Tamer173** [comment]
The problem is that rental papers are not given on purchase so thats why it gives the error of `I can\'t take a vehicle without its papers`

**Comment by amgmacht** [comment]
That's strange, I reloaded the script the day before yesterday and when I borrowed it, he gave me the papers and was able to return them. I did everything myself according to the instructions and it worked. Maybe you did something wrong when inserting? Do you have errors after borrowing?

**Comment by Tamer173** [comment]
> That's strange, I reloaded the script the day before yesterday and when I borrowed it, he gave me the papers and was able to return them. I did everything myself according to the instructions and it worked. Maybe you did something wrong when inserting? Do you have errors after borrowing?

i did everything mentioned in the Read me File and also can you come help in discord

**Comment by Ddev-scripts** [comment]
fixed ;)
